all:
# Run all doc builds in the tests folder:
#   acts a bit as en end-to-end test
	make -C test_docs html
	make -C roots/test_autodoc/ html
	make -C roots/test_classfolder/ html
	make -C roots/test_duplicate_link/ html
	make -C roots/test_module_class_names/ html
	make -C roots/test_no_matlab_src_dir/ html
	make -C roots/test_numad/ html
	make -C roots/test_package_links/ html
	make -C roots/test_package_prefix/ html
	make -C roots/test_pymat/ html
	make -C roots/test_pymat_common_root/ html
	make -C roots/test_skipping_module_members/ html
